### ISSUE TITLE
Unable to run under default java installation in OSX.

### ISSUE THREAD

**Issue by infodel** [malerisch/burp-csj#2]
I believe it is due to OSX using Java6 as a default install and the extension being compiled for Minimum Java7. Installing Java7 on OSX will cause numerous applications to fail and is not supported by Apple.

Here is the Error Provided:

java.lang.UnsupportedClassVersionError: burp/BurpExtender : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at burp.urc.a(Unknown Source)
    at burp.urc.<init>(Unknown Source)
    at burp.huc.a(Unknown Source)
    at burp.buc.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:680)

**Comment by malerisch** [comment]
A new Jar is available which includes multiple changes/updates - link: http://bit.ly/burpcsj0-2 . 
Even though it can be compiled with 1.6 backwards compatibility, there are imported JARs from other distributions (e.g. Selenium) which are not 1.6 compatible, so the issue remains unfixed.
My suggestion is to use 1.7 as well (e.g. you can have an env with multiple JDK versions). I successfully tested BurpCSJ on Burp Pro 1.6.05 with JDK build 1.7.0.67 on OSX 10.8.5.
This is a link from Oracle for installing JDK 1.7 on OSX if it might help - http://docs.oracle.com/javase/7/docs/webnotes/install/mac/mac-jdk.html
